/* Nova Web AI — premium interactions + live pricing integration */
const legacyPricing=document.querySelector('#pricing .pricing-grid');
if(legacyPricing){legacyPricing.innerHTML='';legacyPricing.id='pricing-catalog';}
const header=document.querySelector('.site-header');
const menu=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav-links');
const progress=document.querySelector('.progress');
window.addEventListener('scroll',()=>{header?.classList.toggle('scrolled',scrollY>12);const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=`${max>0?scrollY/max*100:0}%`},{passive:true});
menu?.addEventListener('click',()=>{const open=nav?.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu')});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const field=document.createElement('div');field.className='ambient-field';field.setAttribute('aria-hidden','true');field.innerHTML='<i></i><i></i><i></i><i></i><i></i><i></i>';document.body.prepend(field);
const revealEls=document.querySelectorAll('.reveal');
revealEls.forEach((el,i)=>{el.classList.add('visible');el.style.opacity='1';el.style.visibility='visible';el.style.transform='none';el.style.animation=`localReveal .65s ease ${Math.min(i*.04,.35)}s both`});
const work=document.querySelector('#work');
if(work){work.id='plans';work.className='section container pricing-live';work.innerHTML=`<div class="section-head"><div><span class="kicker">03 / PRICING</span><h2>Build something <span>worth visiting.</span></h2></div><p>Simple, transparent starting points for a professional website. Choose a direction and send your project brief — no recurring website fees.</p></div><div class="pricing-grid"><article class="price-card"><span class="price-label">STARTER</span><h3>1,499 EGP</h3><p>For a focused online presence and a strong first launch.</p><ul><li>One-page website</li><li>Responsive design</li><li>9+ content sections</li><li>Basic custom animations</li><li>Contact section</li></ul><a class="button secondary full" href="#contact" data-plan="Starter Website">Get started <span>↗</span></a></article><article class="price-card recommended"><div class="recommend">RECOMMENDED</div><span class="price-label">BUSINESS</span><h3>2,999 EGP</h3><p>For businesses that need a complete, polished online presence.</p><ul><li>Multi-section website</li><li>Responsive design</li><li>Custom visual direction</li><li>Interactive animations</li><li>Contact form</li><li>SEO-friendly structure</li></ul><a class="button primary full" href="#contact" data-plan="Business Website">Choose Business <span>↗</span></a></article><article class="price-card"><span class="price-label">PREMIUM</span><h3>5,999 EGP</h3><p>For a tailored experience with deeper interaction and customization.</p><ul><li>Custom website experience</li><li>Advanced sections</li><li>Premium VFX and motion</li><li>Custom interactions</li><li>Responsive build</li><li>Priority handling</li></ul><a class="button secondary full" href="#contact" data-plan="Premium Website">Go premium <span>↗</span></a></article></div><p class="pricing-note">Final scope and pricing are confirmed before work begins.</p>`;document.querySelectorAll('.nav-links a[href="#work"]').forEach(a=>a.setAttribute('href','#plans'));document.querySelectorAll('[data-plan]').forEach(a=>a.addEventListener('click',()=>{const desc=document.querySelector('#contactForm [name="description"]');if(desc){desc.value=`I'm interested in the ${a.dataset.plan}.\n\nProject details:`;desc.focus()}}));}
const form=document.getElementById('contactForm');const status=document.querySelector('.form-status');
form?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());const name=(data.name||'there').toString().trim();const button=form.querySelector('button[type=submit]');if(button){button.disabled=true;button.dataset.originalText=button.textContent;button.textContent='Sending…'}if(status)status.textContent='Sending your project request…';try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Unable to send');if(status)status.textContent=`Thanks, ${name||'there'} — your project request has been sent.`;form.reset();if(window.NovaCart?.clear)window.NovaCart.clear()}catch(error){console.error(error);if(status)status.textContent='Something went wrong while sending. Please try again in a moment.'}finally{if(button){button.disabled=false;button.textContent=button.dataset.originalText||'Send Project Request'}}});
document.querySelectorAll('.faq-list details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)document.querySelectorAll('.faq-list details').forEach(other=>{if(other!==d)other.open=false})}));
const commerce=document.createElement('script');commerce.src='commerce.js';document.head.appendChild(commerce);
